safe: true
lsi: false

root_url: http://kushagragour.in
author:
  name: Kushagra Gour
title: Kushagra Gour- Creativity freak!
permalink: /blog/:year/:month/:title/
highlighter: rouge
url: 'https://kushagragour.in'
plugins:
  - jekyll-sitemap
